//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuduMovie.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class huduEntities : DbContext
    {
        public huduEntities()
            : base("name=huduEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actor> actors { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<movie> movies { get; set; }
        public virtual DbSet<movie_actor> movie_actor { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_movie> user_movie { get; set; }
        public virtual DbSet<movie_genre> movie_genre { get; set; }
    }
}
