//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuduMovie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie_actor
    {
        public int movie_id { get; set; }
        public int actor_id { get; set; }
        public int movie_actor_cast { get; set; }
    
        public virtual actor actor { get; set; }
        public virtual movie movie { get; set; }
    }
}
