//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuduMovie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int payment_id { get; set; }
        public int payment_user_id { get; set; }
        public string payment_card_number { get; set; }
        public int payment_card_cvv { get; set; }
        public System.DateTime payement_card_expiry { get; set; }
    
        public virtual user user { get; set; }
    }
}
