//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuduMovie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_movie
    {
        public int user_movies_id { get; set; }
        public int user_id { get; set; }
        public int movie_id { get; set; }
        public System.DateTime movie_rental_expiry { get; set; }
        public Nullable<int> movie_owns { get; set; }
        public System.DateTime movie_tx_date { get; set; }
    
        public virtual movie movie { get; set; }
        public virtual user user { get; set; }
    }
}
