//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuduMovie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.payments = new HashSet<payment>();
            this.user_movie = new HashSet<user_movie>();
        }
    
        public int user_id { get; set; }
        public string user_fname { get; set; }
        public string user_lname { get; set; }
        public Nullable<System.DateTime> user_date_of_birth { get; set; }
        public string user_email { get; set; }
        public string password { get; set; }
        public string passwordhash { get; set; }
        public int role_id { get; set; }
        public int user_is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payments { get; set; }
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_movie> user_movie { get; set; }
    }
}
